M48
; DRILL file {KiCad (6.99.0-2452-gdb4f2d9dd8)} date Tuesday, August 02, 2022 at 10:01:30 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-02T22:01:30-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.99.0-2452-gdb4f2d9dd8)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X67.36Y-60.5
X69.9Y-60.5
T2
X53.26Y-95.93
X53.26Y-98.47
X55.8Y-95.93
X55.8Y-98.47
X58.34Y-95.93
X58.34Y-98.47
T0
M30
